apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: doggy-countdown
  labels:
    app.kubernetes.io/name: doggy-countdown
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doggy-countdown
